// <auto-generated />
using System;
using EquilibraMais.DbConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EquilibraMais.Migrations
{
    [DbContext(typeof(EquilibraMaisDbContext))]
    partial class EquilibraMaisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquilibraMais.Model.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome_empresa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_EMPRESA");

                    b.HasKey("Id");

                    b.ToTable("EMPRESA");
                });

            modelBuilder.Entity("EquilibraMais.Model.Funcionario_Info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carga")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CARGA");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA");

                    b.Property<int>("Energia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ENERGIA");

                    b.Property<string>("Historico_medico")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("HISTORICO_MEDICO");

                    b.Property<int>("Humor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("HUMOR");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<int>("Sono")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SONO");

                    b.Property<int>("Usuario_id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("Usuario_id");

                    b.ToTable("FUNCIONARIO_INFO");
                });

            modelBuilder.Entity("EquilibraMais.Model.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("Empresa_id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMPRESA_ID");

                    b.HasKey("Id");

                    b.HasIndex("Empresa_id");

                    b.ToTable("SETOR");
                });

            modelBuilder.Entity("EquilibraMais.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CARGO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<int>("Setor_id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SETOR_ID");

                    b.HasKey("Id");

                    b.HasIndex("Setor_id");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("EquilibraMais.Model.Funcionario_Info", b =>
                {
                    b.HasOne("EquilibraMais.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EquilibraMais.Model.Setor", b =>
                {
                    b.HasOne("EquilibraMais.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("Empresa_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SETOR_EMPRESA");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("EquilibraMais.Model.Usuario", b =>
                {
                    b.HasOne("EquilibraMais.Model.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("Setor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USUARIO_SETOR");

                    b.Navigation("Setor");
                });
#pragma warning restore 612, 618
        }
    }
}
